# Generated by Django 3.1 on 2020-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.JSONField()),
                ('weather', models.JSONField()),
                ('main', models.JSONField()),
                ('wind', models.JSONField()),
                ('clouds', models.JSONField()),
                ('sys', models.JSONField()),
                ('base', models.CharField(max_length=20)),
                ('visibility', models.IntegerField()),
                ('dt', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
